services:
  agentstudio:
    build:
      context: .
      dockerfile: agentstudio/Dockerfile
    ports:
      - "2024:2024"
    environment:
      - OPENAI_API_KEY
      - TAVILY_API_KEY
      - LANGSMITH_PROJECT
      - LANGSMITH_API_KEY
      - LANGSMITH_TRACING
      - LANGSMITH_ENDPOINT

  ragservice:
    build:
      context: .
      dockerfile: ragservice/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY


  stsservice:
    build:
      context: .
      dockerfile: stsservice/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - agentstudio
    environment:
      - OPENAI_API_KEY
      - LANGGRAPH_URL=http://agentstudio:2024